# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
    build_app(scheme: "SOS Flashlight & Morse Code")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end
end

lane :certs do
    update_project_team(
      path: "SOS Flashlight & Morse Code.xcodeproj",
      teamid: "GEKZN86RYS"
    )
    match(type: "appstore", app_identifier: ["com.whizbang.SOS-Flashlight---Morse-Code"])
    match(type: "development", app_identifier: ["com.whizbang.SOS-Flashlight---Morse-Code"])
    match(type: "adhoc", app_identifier: ["com.whizbang.SOS-Flashlight---Morse-Code"])
  end

  desc "App Store Release"
  lane :release do
    # enable_automatic_code_signing
    get_provisioning_profile(app_identifier: "com.whizbang.SOS-Flashlight---Morse-Code")

    increment_build_number
    increment_version_number(
      # bump_type: "minor"
      version_number: "1.41"
    )

    build_app(
      workspace: "SOS Flashlight & Morse Code.xcworkspace",
      scheme: "SOS Flashlight & Morse Code",
      include_bitcode: true,
      export_xcargs: "-allowProvisioningUpdates",
    )


    upload_to_app_store
  end
